//////////////////////////////////////////////////////////////////////
//
// evcl - boot - Symbol in Keyword Package
// boot/package_keyword.inc
//
// This file is part of Evita Common Lisp.
//
// Copyright (C) 1996-2007 by Project Vogue.
// Written by Yoshifumi "VOGUE" INOUE. (yosi@msn.com)
//
// @(#)$Id: /proj/evcl3/boot/bt_package_keyword.inc 25 2006-10-19 11:25:45 yosi $
//
L"32BIT",               // *features*
L"64BIT",               // *features*
L"ABORT",               // close
L"ADDRESS",             // platform-exception
L"AGE",                 // gc
L"ALLOW-OTHER-KEYS",    // &key
L"APPEND",              // open
L"BIG-ENDIAN",          // *features*
L"CODE",                // platform-exception
L"COMPILE-TOPLEVEL",    // eval-when
L"COMPILE-TIME-TOO",    // eval-when
L"COMPILER-MACRO",      // compiler-macro-function
L"COMPLETED",           // completed
L"COUNT",               // compiler
L"DEFAULT",             // room
L"ERROR",               // open
L"EXECUTE",             // eval-when
L"EXTERNAL-FORMAT",     // open
L"FINALLY",             // compiler - unwind-protect
L"FUNCTION",            // compiler
L"HEAP",                // compiler
L"IF-EXISTS",           // open
L"IF-DOES-NOT-EXIST",   // open
L"INDEX",               // bounding-index-error
L"IP",                  // platform-exception
L"LITTLE-ENDIAN",       // *features*
L"KEY",                 // &key
L"KEYS",                // &key
L"NAME",                // undefined-function
L"NEW-VERSION",         // open
L"NONE",                // compiler - ENTRY and PROLOGUE
L"NOT-COMPILE-TIME",    // eval-when
L"LOAD-TOPLEVEL",       // eval-when
L"OPERANDS",            // arithmetic-erro
L"OPERATION",           // arithmetic-erro
L"RENAME",              // open
L"RENAME-AND-DELETE",   // open
L"SCHEDULED",           // finalization
L"STACK",               // compiler
L"SUPERSEDE",           // open
L"SYMBOL-MACRO",        // compiler
L"TOPLEVEL",            // compiler
L"UNSCHEDULED",         // finalization
