//////////////////////////////////////////////////////////////////////////////
//
// evcl - compiler - x64 - IR Operation Code
// arch/x64/compiler/x64_ir_opcode.h
//
// Copyright (C) 1996-2006 by Project Vogue.
// Written by Yoshifumi "VOGUE" INOUE. (yosi@msn.com)
//
// @(#)$Id: //proj/evcl3/mainline/arch/x64/compiler/x64_ir_opcode.inc#5 $
//
#include "../../x86x64/compiler/x86x64_ir_opcode.inc"
